### ISSUE TITLE
Datalist Not working or showing

### ISSUE THREAD

**Issue by rohangyemul** [cztomczak/phpdesktop#295] opened 2021-01-31 11:19 UTC
Questions should be asked on the forum:
https://groups.google.com/d/forum/phpdesktop

```
<!DOCTYPE html>
<html>
<body>

<h2>The datalist Element</h2>

<p>The datalist element specifies a list of pre-defined options for an input element.</p>

<form action="/action_page.php">
  <input list="browsers" name="browser">
  <datalist id="browsers">
    <option value="Internet Explorer">
    <option value="Firefox">
    <option value="Chrome">
    <option value="Opera">
    <option value="Safari">
  </datalist>
  <input type="submit">
</form>

<p><b>Note:</b> The datalist tag is not supported in Safari prior version 12.1.</p>

</body>
</html>
```

**THIS ABOVE CODE NOT WORKING**

**Comment by cztomczak** [comment] 2021-11-08 16:33
Some of HTML 5 widgets are not supported by Chromium Embedded Framework. This may be fixed when we upgrade to newer CEF version.

**Comment by cztomczak** [comment] 2021-11-08 16:34
Duplicate of https://github.com/cztomczak/phpdesktop/issues/209 .

**Closed by cztomczak** 2021-11-08 16:34 UTC
