### ISSUE TITLE
starting app minimized

### ISSUE THREAD

**Issue by soufi7** [cztomczak/phpdesktop#283] opened 2020-09-11 09:54 UTC
Would it be possible to add an option to auto start app minimized to tray?

**Comment by inprovo** [comment] 2020-10-21 15:26
I would also like this feature!

**Comment by cztomczak** [comment] 2021-11-08 16:40
Duplicate of https://github.com/cztomczak/phpdesktop/issues/199 .

**Closed by cztomczak** 2021-11-08 16:40 UTC
Labels: feature
