### ISSUE TITLE
Where do I get the version for Mac?

### ISSUE THREAD

**Issue by DioneLago** [cztomczak/phpdesktop#194] opened 2016-09-15 20:11 UTC
I liked the project, as did small tests, very good! But I tried to download a version of the same for Mac and have not found, there is only downloads with .exe, is there a version for Mac? If so, where meeting someone can help me?

**Comment by ZanderBrown** [comment] 2016-09-15 22:12
You don't get it because it doesn't exist.

**Comment by cztomczak** [comment] 2016-09-15 23:13
Only Windows platform is supported so far. Duplicate of #78 . There isn't much stopping from porting phpdesktop to Mac, only time and effort, all dependent libraries like Mongoose web server and Chromium Embedded Framework are supported on both Mac/Linux. Porting to Mac with basic settings support, without  all the advanced options from settings.json / js api, should be straightforward to do, in a matter of days I think. I have a Mac, but I don't use it too much, some day I may work on this port. Pull requests are welcome of course if someone would like to take this effort.

**Closed by cztomczak** 2016-09-15 23:13 UTC

**Comment by DioneLago** [comment] 2016-09-15 23:36
Guys, thanks for the clarification. If there is the possibility of a version for Mac and Linux would be perfect, PHP is a language for decades and is still very active in the market, I believe it would be possible to meet the demand for small business applications with simple solutions. @cztomczak congratulations here by made.

**Comment by carmenchapa** [comment] 2017-03-16 17:16
Guys, this project seems awesome. So sad it is not supported by Mac. It would be really useful for me.

**Comment by svnpenn** [comment] 2017-10-12 00:21
https://github.com/cztomczak/phpdesktop/issues/169

**Comment by svnpenn** [comment] 2017-10-12 00:22
https://github.com/cztomczak/phpdesktop/issues/208

**Comment by cztomczak** [comment] 2024-11-09 18:27
@s22-tech Current status on screenshot attached. Basically it works. Still a few things to fix before release.

![image](https://github.com/user-attachments/assets/a6f8dee1-9f5f-4d3f-8d78-a975e49125ce)
