### ISSUE TITLE
Microphone is not accessible

### ISSUE THREAD

**Issue by anandreddyks** [cztomczak/phpdesktop#191] opened 2016-08-19 09:50 UTC
I cant access microphone after adding the enable-speech in command_line_switches @settings.json. 

I tried with these websites . . 
https://www.talater.com/annyang/
https://www.onlinemictest.com/

**Comment by cztomczak** [comment] 2016-08-19 11:44
Looks like a duplicate of #75. Please report problems on the Forum.

**Closed by cztomczak** 2016-08-19 11:44 UTC
